filebeat.inputs:
- type: log
  enabled: true
  paths:
    - /var/jenkins_home/jenkins-*.log.*
  multiline.pattern: '^[A-Z]{1}[a-z]{2} {1,2}[0-9]{1,2}, [0-9]{4} {1,2}[0-9]{1,2}:[0-9]{2}:[0-9]{2}'
  multiline.negate: true
  multiline.match: after

output.elasticsearch:
  hosts: ['elasticsearch:9200']
  username: elastic
  password: changeme
